dist: trusty
language: node_js
sudo: false

addons:
  chrome: stable

cache:
  directories:
  - $HOME/.npm

branches:
  only:
  - master

node_js:
- 10

before_install:
- npm i -g npm@^6.0.0

before_script:
- npm prune

script:
- npm run test:lib-coverage # Run regular testing and output code coverage report
- npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist/ngx-ratio-bar-showcase
  on:
    branch: master

git:
  depth: 3

after_success:
- npm run report-coverage
- npm run travis-deploy-once "npm run semantic-release"

